# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: swarndb/v1/common.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'swarndb/v1/common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17swarndb/v1/common.proto\x12\nswarndb.v1\"\x18\n\x06Vector\x12\x0e\n\x06values\x18\x01 \x03(\x02\"\x86\x01\n\x08Metadata\x12\x30\n\x06\x66ields\x18\x01 \x03(\x0b\x32 .swarndb.v1.Metadata.FieldsEntry\x1aH\n\x0b\x46ieldsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12(\n\x05value\x18\x02 \x01(\x0b\x32\x19.swarndb.v1.MetadataValue:\x02\x38\x01\"\xa7\x01\n\rMetadataValue\x12\x16\n\x0cstring_value\x18\x01 \x01(\tH\x00\x12\x13\n\tint_value\x18\x02 \x01(\x03H\x00\x12\x15\n\x0b\x66loat_value\x18\x03 \x01(\x01H\x00\x12\x14\n\nbool_value\x18\x04 \x01(\x08H\x00\x12\x33\n\x11string_list_value\x18\x05 \x01(\x0b\x32\x16.swarndb.v1.StringListH\x00\x42\x07\n\x05value\"\x1c\n\nStringList\x12\x0e\n\x06values\x18\x01 \x03(\t\"4\n\x0bRelatedEdge\x12\x11\n\ttarget_id\x18\x01 \x01(\x04\x12\x12\n\nsimilarity\x18\x02 \x01(\x02\"\x7f\n\x0cScoredResult\x12\n\n\x02id\x18\x01 \x01(\x04\x12\r\n\x05score\x18\x02 \x01(\x02\x12&\n\x08metadata\x18\x03 \x01(\x0b\x32\x14.swarndb.v1.Metadata\x12,\n\x0bgraph_edges\x18\x04 \x03(\x0b\x32\x17.swarndb.v1.RelatedEdgeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'swarndb.v1.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_METADATA_FIELDSENTRY']._loaded_options = None
  _globals['_METADATA_FIELDSENTRY']._serialized_options = b'8\001'
  _globals['_VECTOR']._serialized_start=39
  _globals['_VECTOR']._serialized_end=63
  _globals['_METADATA']._serialized_start=66
  _globals['_METADATA']._serialized_end=200
  _globals['_METADATA_FIELDSENTRY']._serialized_start=128
  _globals['_METADATA_FIELDSENTRY']._serialized_end=200
  _globals['_METADATAVALUE']._serialized_start=203
  _globals['_METADATAVALUE']._serialized_end=370
  _globals['_STRINGLIST']._serialized_start=372
  _globals['_STRINGLIST']._serialized_end=400
  _globals['_RELATEDEDGE']._serialized_start=402
  _globals['_RELATEDEDGE']._serialized_end=454
  _globals['_SCOREDRESULT']._serialized_start=456
  _globals['_SCOREDRESULT']._serialized_end=583
# @@protoc_insertion_point(module_scope)
