# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import extraction_pb2 as swarndb_dot_v1_dot_extraction__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in swarndb/v1/extraction_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ExtractionServiceStub(object):
    """LLM extraction service (Hybrid mode only). Additive new file; it shares the
    swarndb.v1 package but defines no field numbers that collide with existing
    services. Every RPC is rejected with FailedPrecondition on non-Hybrid
    collections.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetLlmConfig = channel.unary_unary(
                '/swarndb.v1.ExtractionService/SetLlmConfig',
                request_serializer=swarndb_dot_v1_dot_extraction__pb2.SetLlmConfigRequest.SerializeToString,
                response_deserializer=swarndb_dot_v1_dot_extraction__pb2.SetLlmConfigResponse.FromString,
                _registered_method=True)
        self.GetLlmConfig = channel.unary_unary(
                '/swarndb.v1.ExtractionService/GetLlmConfig',
                request_serializer=swarndb_dot_v1_dot_extraction__pb2.GetLlmConfigRequest.SerializeToString,
                response_deserializer=swarndb_dot_v1_dot_extraction__pb2.GetLlmConfigResponse.FromString,
                _registered_method=True)
        self.RotateLlmConfig = channel.unary_unary(
                '/swarndb.v1.ExtractionService/RotateLlmConfig',
                request_serializer=swarndb_dot_v1_dot_extraction__pb2.RotateLlmConfigRequest.SerializeToString,
                response_deserializer=swarndb_dot_v1_dot_extraction__pb2.RotateLlmConfigResponse.FromString,
                _registered_method=True)
        self.SetOntology = channel.unary_unary(
                '/swarndb.v1.ExtractionService/SetOntology',
                request_serializer=swarndb_dot_v1_dot_extraction__pb2.SetOntologyRequest.SerializeToString,
                response_deserializer=swarndb_dot_v1_dot_extraction__pb2.SetOntologyResponse.FromString,
                _registered_method=True)
        self.GetOntology = channel.unary_unary(
                '/swarndb.v1.ExtractionService/GetOntology',
                request_serializer=swarndb_dot_v1_dot_extraction__pb2.GetOntologyRequest.SerializeToString,
                response_deserializer=swarndb_dot_v1_dot_extraction__pb2.GetOntologyResponse.FromString,
                _registered_method=True)
        self.CostPreview = channel.unary_unary(
                '/swarndb.v1.ExtractionService/CostPreview',
                request_serializer=swarndb_dot_v1_dot_extraction__pb2.CostPreviewRequest.SerializeToString,
                response_deserializer=swarndb_dot_v1_dot_extraction__pb2.CostPreviewResponse.FromString,
                _registered_method=True)
        self.StartExtraction = channel.unary_unary(
                '/swarndb.v1.ExtractionService/StartExtraction',
                request_serializer=swarndb_dot_v1_dot_extraction__pb2.StartExtractionRequest.SerializeToString,
                response_deserializer=swarndb_dot_v1_dot_extraction__pb2.StartExtractionResponse.FromString,
                _registered_method=True)
        self.AppendExtractionChunks = channel.unary_unary(
                '/swarndb.v1.ExtractionService/AppendExtractionChunks',
                request_serializer=swarndb_dot_v1_dot_extraction__pb2.AppendExtractionChunksRequest.SerializeToString,
                response_deserializer=swarndb_dot_v1_dot_extraction__pb2.AppendExtractionChunksResponse.FromString,
                _registered_method=True)
        self.GetExtractionStatus = channel.unary_unary(
                '/swarndb.v1.ExtractionService/GetExtractionStatus',
                request_serializer=swarndb_dot_v1_dot_extraction__pb2.GetExtractionStatusRequest.SerializeToString,
                response_deserializer=swarndb_dot_v1_dot_extraction__pb2.JobStatusMsg.FromString,
                _registered_method=True)
        self.CancelExtraction = channel.unary_unary(
                '/swarndb.v1.ExtractionService/CancelExtraction',
                request_serializer=swarndb_dot_v1_dot_extraction__pb2.CancelExtractionRequest.SerializeToString,
                response_deserializer=swarndb_dot_v1_dot_extraction__pb2.CancelExtractionResponse.FromString,
                _registered_method=True)
        self.ListProposals = channel.unary_unary(
                '/swarndb.v1.ExtractionService/ListProposals',
                request_serializer=swarndb_dot_v1_dot_extraction__pb2.ListProposalsRequest.SerializeToString,
                response_deserializer=swarndb_dot_v1_dot_extraction__pb2.ListProposalsResponse.FromString,
                _registered_method=True)
        self.ApproveProposal = channel.unary_unary(
                '/swarndb.v1.ExtractionService/ApproveProposal',
                request_serializer=swarndb_dot_v1_dot_extraction__pb2.ApproveProposalRequest.SerializeToString,
                response_deserializer=swarndb_dot_v1_dot_extraction__pb2.ApproveProposalResponse.FromString,
                _registered_method=True)
        self.RejectProposal = channel.unary_unary(
                '/swarndb.v1.ExtractionService/RejectProposal',
                request_serializer=swarndb_dot_v1_dot_extraction__pb2.RejectProposalRequest.SerializeToString,
                response_deserializer=swarndb_dot_v1_dot_extraction__pb2.RejectProposalResponse.FromString,
                _registered_method=True)
        self.DiffDocument = channel.unary_unary(
                '/swarndb.v1.ExtractionService/DiffDocument',
                request_serializer=swarndb_dot_v1_dot_extraction__pb2.DiffDocumentRequest.SerializeToString,
                response_deserializer=swarndb_dot_v1_dot_extraction__pb2.DiffDocumentResponse.FromString,
                _registered_method=True)
        self.ReextractDocument = channel.unary_unary(
                '/swarndb.v1.ExtractionService/ReextractDocument',
                request_serializer=swarndb_dot_v1_dot_extraction__pb2.ReextractDocumentRequest.SerializeToString,
                response_deserializer=swarndb_dot_v1_dot_extraction__pb2.ReextractDocumentResponse.FromString,
                _registered_method=True)
        self.StartCorpusReextraction = channel.unary_unary(
                '/swarndb.v1.ExtractionService/StartCorpusReextraction',
                request_serializer=swarndb_dot_v1_dot_extraction__pb2.StartCorpusReextractionRequest.SerializeToString,
                response_deserializer=swarndb_dot_v1_dot_extraction__pb2.StartCorpusReextractionResponse.FromString,
                _registered_method=True)
        self.GetCorpusReextractionStatus = channel.unary_unary(
                '/swarndb.v1.ExtractionService/GetCorpusReextractionStatus',
                request_serializer=swarndb_dot_v1_dot_extraction__pb2.GetCorpusReextractionStatusRequest.SerializeToString,
                response_deserializer=swarndb_dot_v1_dot_extraction__pb2.CorpusReextractionStatusMsg.FromString,
                _registered_method=True)
        self.CancelCorpusReextraction = channel.unary_unary(
                '/swarndb.v1.ExtractionService/CancelCorpusReextraction',
                request_serializer=swarndb_dot_v1_dot_extraction__pb2.CancelCorpusReextractionRequest.SerializeToString,
                response_deserializer=swarndb_dot_v1_dot_extraction__pb2.CancelCorpusReextractionResponse.FromString,
                _registered_method=True)


class ExtractionServiceServicer(object):
    """LLM extraction service (Hybrid mode only). Additive new file; it shares the
    swarndb.v1 package but defines no field numbers that collide with existing
    services. Every RPC is rejected with FailedPrecondition on non-Hybrid
    collections.
    """

    def SetLlmConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLlmConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RotateLlmConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetOntology(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOntology(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CostPreview(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartExtraction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AppendExtractionChunks(self, request, context):
        """ADR-013. Append more chunks to an existing job across several messages.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetExtractionStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelExtraction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListProposals(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApproveProposal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RejectProposal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DiffDocument(self, request, context):
        """P04. Additive document-update detection and re-extraction.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReextractDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartCorpusReextraction(self, request, context):
        """P16 (Area 3). Additive corpus-level, resumable re-extraction over a set of
        documents or a whole collection. Single-document ReextractDocument is
        unchanged; this drives that same path per document.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCorpusReextractionStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelCorpusReextraction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExtractionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetLlmConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.SetLlmConfig,
                    request_deserializer=swarndb_dot_v1_dot_extraction__pb2.SetLlmConfigRequest.FromString,
                    response_serializer=swarndb_dot_v1_dot_extraction__pb2.SetLlmConfigResponse.SerializeToString,
            ),
            'GetLlmConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLlmConfig,
                    request_deserializer=swarndb_dot_v1_dot_extraction__pb2.GetLlmConfigRequest.FromString,
                    response_serializer=swarndb_dot_v1_dot_extraction__pb2.GetLlmConfigResponse.SerializeToString,
            ),
            'RotateLlmConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.RotateLlmConfig,
                    request_deserializer=swarndb_dot_v1_dot_extraction__pb2.RotateLlmConfigRequest.FromString,
                    response_serializer=swarndb_dot_v1_dot_extraction__pb2.RotateLlmConfigResponse.SerializeToString,
            ),
            'SetOntology': grpc.unary_unary_rpc_method_handler(
                    servicer.SetOntology,
                    request_deserializer=swarndb_dot_v1_dot_extraction__pb2.SetOntologyRequest.FromString,
                    response_serializer=swarndb_dot_v1_dot_extraction__pb2.SetOntologyResponse.SerializeToString,
            ),
            'GetOntology': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOntology,
                    request_deserializer=swarndb_dot_v1_dot_extraction__pb2.GetOntologyRequest.FromString,
                    response_serializer=swarndb_dot_v1_dot_extraction__pb2.GetOntologyResponse.SerializeToString,
            ),
            'CostPreview': grpc.unary_unary_rpc_method_handler(
                    servicer.CostPreview,
                    request_deserializer=swarndb_dot_v1_dot_extraction__pb2.CostPreviewRequest.FromString,
                    response_serializer=swarndb_dot_v1_dot_extraction__pb2.CostPreviewResponse.SerializeToString,
            ),
            'StartExtraction': grpc.unary_unary_rpc_method_handler(
                    servicer.StartExtraction,
                    request_deserializer=swarndb_dot_v1_dot_extraction__pb2.StartExtractionRequest.FromString,
                    response_serializer=swarndb_dot_v1_dot_extraction__pb2.StartExtractionResponse.SerializeToString,
            ),
            'AppendExtractionChunks': grpc.unary_unary_rpc_method_handler(
                    servicer.AppendExtractionChunks,
                    request_deserializer=swarndb_dot_v1_dot_extraction__pb2.AppendExtractionChunksRequest.FromString,
                    response_serializer=swarndb_dot_v1_dot_extraction__pb2.AppendExtractionChunksResponse.SerializeToString,
            ),
            'GetExtractionStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetExtractionStatus,
                    request_deserializer=swarndb_dot_v1_dot_extraction__pb2.GetExtractionStatusRequest.FromString,
                    response_serializer=swarndb_dot_v1_dot_extraction__pb2.JobStatusMsg.SerializeToString,
            ),
            'CancelExtraction': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelExtraction,
                    request_deserializer=swarndb_dot_v1_dot_extraction__pb2.CancelExtractionRequest.FromString,
                    response_serializer=swarndb_dot_v1_dot_extraction__pb2.CancelExtractionResponse.SerializeToString,
            ),
            'ListProposals': grpc.unary_unary_rpc_method_handler(
                    servicer.ListProposals,
                    request_deserializer=swarndb_dot_v1_dot_extraction__pb2.ListProposalsRequest.FromString,
                    response_serializer=swarndb_dot_v1_dot_extraction__pb2.ListProposalsResponse.SerializeToString,
            ),
            'ApproveProposal': grpc.unary_unary_rpc_method_handler(
                    servicer.ApproveProposal,
                    request_deserializer=swarndb_dot_v1_dot_extraction__pb2.ApproveProposalRequest.FromString,
                    response_serializer=swarndb_dot_v1_dot_extraction__pb2.ApproveProposalResponse.SerializeToString,
            ),
            'RejectProposal': grpc.unary_unary_rpc_method_handler(
                    servicer.RejectProposal,
                    request_deserializer=swarndb_dot_v1_dot_extraction__pb2.RejectProposalRequest.FromString,
                    response_serializer=swarndb_dot_v1_dot_extraction__pb2.RejectProposalResponse.SerializeToString,
            ),
            'DiffDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.DiffDocument,
                    request_deserializer=swarndb_dot_v1_dot_extraction__pb2.DiffDocumentRequest.FromString,
                    response_serializer=swarndb_dot_v1_dot_extraction__pb2.DiffDocumentResponse.SerializeToString,
            ),
            'ReextractDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.ReextractDocument,
                    request_deserializer=swarndb_dot_v1_dot_extraction__pb2.ReextractDocumentRequest.FromString,
                    response_serializer=swarndb_dot_v1_dot_extraction__pb2.ReextractDocumentResponse.SerializeToString,
            ),
            'StartCorpusReextraction': grpc.unary_unary_rpc_method_handler(
                    servicer.StartCorpusReextraction,
                    request_deserializer=swarndb_dot_v1_dot_extraction__pb2.StartCorpusReextractionRequest.FromString,
                    response_serializer=swarndb_dot_v1_dot_extraction__pb2.StartCorpusReextractionResponse.SerializeToString,
            ),
            'GetCorpusReextractionStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCorpusReextractionStatus,
                    request_deserializer=swarndb_dot_v1_dot_extraction__pb2.GetCorpusReextractionStatusRequest.FromString,
                    response_serializer=swarndb_dot_v1_dot_extraction__pb2.CorpusReextractionStatusMsg.SerializeToString,
            ),
            'CancelCorpusReextraction': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelCorpusReextraction,
                    request_deserializer=swarndb_dot_v1_dot_extraction__pb2.CancelCorpusReextractionRequest.FromString,
                    response_serializer=swarndb_dot_v1_dot_extraction__pb2.CancelCorpusReextractionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swarndb.v1.ExtractionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('swarndb.v1.ExtractionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ExtractionService(object):
    """LLM extraction service (Hybrid mode only). Additive new file; it shares the
    swarndb.v1 package but defines no field numbers that collide with existing
    services. Every RPC is rejected with FailedPrecondition on non-Hybrid
    collections.
    """

    @staticmethod
    def SetLlmConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swarndb.v1.ExtractionService/SetLlmConfig',
            swarndb_dot_v1_dot_extraction__pb2.SetLlmConfigRequest.SerializeToString,
            swarndb_dot_v1_dot_extraction__pb2.SetLlmConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLlmConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swarndb.v1.ExtractionService/GetLlmConfig',
            swarndb_dot_v1_dot_extraction__pb2.GetLlmConfigRequest.SerializeToString,
            swarndb_dot_v1_dot_extraction__pb2.GetLlmConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RotateLlmConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swarndb.v1.ExtractionService/RotateLlmConfig',
            swarndb_dot_v1_dot_extraction__pb2.RotateLlmConfigRequest.SerializeToString,
            swarndb_dot_v1_dot_extraction__pb2.RotateLlmConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetOntology(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swarndb.v1.ExtractionService/SetOntology',
            swarndb_dot_v1_dot_extraction__pb2.SetOntologyRequest.SerializeToString,
            swarndb_dot_v1_dot_extraction__pb2.SetOntologyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOntology(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swarndb.v1.ExtractionService/GetOntology',
            swarndb_dot_v1_dot_extraction__pb2.GetOntologyRequest.SerializeToString,
            swarndb_dot_v1_dot_extraction__pb2.GetOntologyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CostPreview(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swarndb.v1.ExtractionService/CostPreview',
            swarndb_dot_v1_dot_extraction__pb2.CostPreviewRequest.SerializeToString,
            swarndb_dot_v1_dot_extraction__pb2.CostPreviewResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartExtraction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swarndb.v1.ExtractionService/StartExtraction',
            swarndb_dot_v1_dot_extraction__pb2.StartExtractionRequest.SerializeToString,
            swarndb_dot_v1_dot_extraction__pb2.StartExtractionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AppendExtractionChunks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swarndb.v1.ExtractionService/AppendExtractionChunks',
            swarndb_dot_v1_dot_extraction__pb2.AppendExtractionChunksRequest.SerializeToString,
            swarndb_dot_v1_dot_extraction__pb2.AppendExtractionChunksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetExtractionStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swarndb.v1.ExtractionService/GetExtractionStatus',
            swarndb_dot_v1_dot_extraction__pb2.GetExtractionStatusRequest.SerializeToString,
            swarndb_dot_v1_dot_extraction__pb2.JobStatusMsg.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelExtraction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swarndb.v1.ExtractionService/CancelExtraction',
            swarndb_dot_v1_dot_extraction__pb2.CancelExtractionRequest.SerializeToString,
            swarndb_dot_v1_dot_extraction__pb2.CancelExtractionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListProposals(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swarndb.v1.ExtractionService/ListProposals',
            swarndb_dot_v1_dot_extraction__pb2.ListProposalsRequest.SerializeToString,
            swarndb_dot_v1_dot_extraction__pb2.ListProposalsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ApproveProposal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swarndb.v1.ExtractionService/ApproveProposal',
            swarndb_dot_v1_dot_extraction__pb2.ApproveProposalRequest.SerializeToString,
            swarndb_dot_v1_dot_extraction__pb2.ApproveProposalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RejectProposal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swarndb.v1.ExtractionService/RejectProposal',
            swarndb_dot_v1_dot_extraction__pb2.RejectProposalRequest.SerializeToString,
            swarndb_dot_v1_dot_extraction__pb2.RejectProposalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DiffDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swarndb.v1.ExtractionService/DiffDocument',
            swarndb_dot_v1_dot_extraction__pb2.DiffDocumentRequest.SerializeToString,
            swarndb_dot_v1_dot_extraction__pb2.DiffDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReextractDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swarndb.v1.ExtractionService/ReextractDocument',
            swarndb_dot_v1_dot_extraction__pb2.ReextractDocumentRequest.SerializeToString,
            swarndb_dot_v1_dot_extraction__pb2.ReextractDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartCorpusReextraction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swarndb.v1.ExtractionService/StartCorpusReextraction',
            swarndb_dot_v1_dot_extraction__pb2.StartCorpusReextractionRequest.SerializeToString,
            swarndb_dot_v1_dot_extraction__pb2.StartCorpusReextractionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCorpusReextractionStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swarndb.v1.ExtractionService/GetCorpusReextractionStatus',
            swarndb_dot_v1_dot_extraction__pb2.GetCorpusReextractionStatusRequest.SerializeToString,
            swarndb_dot_v1_dot_extraction__pb2.CorpusReextractionStatusMsg.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelCorpusReextraction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swarndb.v1.ExtractionService/CancelCorpusReextraction',
            swarndb_dot_v1_dot_extraction__pb2.CancelCorpusReextractionRequest.SerializeToString,
            swarndb_dot_v1_dot_extraction__pb2.CancelCorpusReextractionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
