# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import graph_pb2 as swarndb_dot_v1_dot_graph__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in swarndb/v1/graph_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GraphServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRelated = channel.unary_unary(
                '/swarndb.v1.GraphService/GetRelated',
                request_serializer=swarndb_dot_v1_dot_graph__pb2.GetRelatedRequest.SerializeToString,
                response_deserializer=swarndb_dot_v1_dot_graph__pb2.GetRelatedResponse.FromString,
                _registered_method=True)
        self.Traverse = channel.unary_unary(
                '/swarndb.v1.GraphService/Traverse',
                request_serializer=swarndb_dot_v1_dot_graph__pb2.TraverseRequest.SerializeToString,
                response_deserializer=swarndb_dot_v1_dot_graph__pb2.TraverseResponse.FromString,
                _registered_method=True)
        self.SetThreshold = channel.unary_unary(
                '/swarndb.v1.GraphService/SetThreshold',
                request_serializer=swarndb_dot_v1_dot_graph__pb2.SetThresholdRequest.SerializeToString,
                response_deserializer=swarndb_dot_v1_dot_graph__pb2.SetThresholdResponse.FromString,
                _registered_method=True)


class GraphServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetRelated(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Traverse(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetThreshold(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GraphServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRelated': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRelated,
                    request_deserializer=swarndb_dot_v1_dot_graph__pb2.GetRelatedRequest.FromString,
                    response_serializer=swarndb_dot_v1_dot_graph__pb2.GetRelatedResponse.SerializeToString,
            ),
            'Traverse': grpc.unary_unary_rpc_method_handler(
                    servicer.Traverse,
                    request_deserializer=swarndb_dot_v1_dot_graph__pb2.TraverseRequest.FromString,
                    response_serializer=swarndb_dot_v1_dot_graph__pb2.TraverseResponse.SerializeToString,
            ),
            'SetThreshold': grpc.unary_unary_rpc_method_handler(
                    servicer.SetThreshold,
                    request_deserializer=swarndb_dot_v1_dot_graph__pb2.SetThresholdRequest.FromString,
                    response_serializer=swarndb_dot_v1_dot_graph__pb2.SetThresholdResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swarndb.v1.GraphService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('swarndb.v1.GraphService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GraphService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetRelated(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swarndb.v1.GraphService/GetRelated',
            swarndb_dot_v1_dot_graph__pb2.GetRelatedRequest.SerializeToString,
            swarndb_dot_v1_dot_graph__pb2.GetRelatedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Traverse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swarndb.v1.GraphService/Traverse',
            swarndb_dot_v1_dot_graph__pb2.TraverseRequest.SerializeToString,
            swarndb_dot_v1_dot_graph__pb2.TraverseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetThreshold(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swarndb.v1.GraphService/SetThreshold',
            swarndb_dot_v1_dot_graph__pb2.SetThresholdRequest.SerializeToString,
            swarndb_dot_v1_dot_graph__pb2.SetThresholdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
