# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: swarndb/v1/graph.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'swarndb/v1/graph.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as swarndb_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16swarndb/v1/graph.proto\x12\nswarndb.v1\x1a\x17swarndb/v1/common.proto\"b\n\x11GetRelatedRequest\x12\x12\n\ncollection\x18\x01 \x01(\t\x12\x11\n\tvector_id\x18\x02 \x01(\x04\x12\x11\n\tthreshold\x18\x03 \x01(\x02\x12\x13\n\x0bmax_results\x18\x04 \x01(\r\"2\n\tGraphEdge\x12\x11\n\ttarget_id\x18\x01 \x01(\x04\x12\x12\n\nsimilarity\x18\x02 \x01(\x02\":\n\x12GetRelatedResponse\x12$\n\x05\x65\x64ges\x18\x01 \x03(\x0b\x32\x15.swarndb.v1.GraphEdge\"n\n\x0fTraverseRequest\x12\x12\n\ncollection\x18\x01 \x01(\t\x12\x10\n\x08start_id\x18\x02 \x01(\x04\x12\r\n\x05\x64\x65pth\x18\x03 \x01(\r\x12\x11\n\tthreshold\x18\x04 \x01(\x02\x12\x13\n\x0bmax_results\x18\x05 \x01(\r\"Q\n\rTraversalNode\x12\n\n\x02id\x18\x01 \x01(\x04\x12\r\n\x05\x64\x65pth\x18\x02 \x01(\r\x12\x17\n\x0fpath_similarity\x18\x03 \x01(\x02\x12\x0c\n\x04path\x18\x04 \x03(\x04\"<\n\x10TraverseResponse\x12(\n\x05nodes\x18\x01 \x03(\x0b\x32\x19.swarndb.v1.TraversalNode\"O\n\x13SetThresholdRequest\x12\x12\n\ncollection\x18\x01 \x01(\t\x12\x11\n\tvector_id\x18\x02 \x01(\x04\x12\x11\n\tthreshold\x18\x03 \x01(\x02\"\'\n\x14SetThresholdResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xf5\x01\n\x0cGraphService\x12K\n\nGetRelated\x12\x1d.swarndb.v1.GetRelatedRequest\x1a\x1e.swarndb.v1.GetRelatedResponse\x12\x45\n\x08Traverse\x12\x1b.swarndb.v1.TraverseRequest\x1a\x1c.swarndb.v1.TraverseResponse\x12Q\n\x0cSetThreshold\x12\x1f.swarndb.v1.SetThresholdRequest\x1a .swarndb.v1.SetThresholdResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'swarndb.v1.graph_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETRELATEDREQUEST']._serialized_start=63
  _globals['_GETRELATEDREQUEST']._serialized_end=161
  _globals['_GRAPHEDGE']._serialized_start=163
  _globals['_GRAPHEDGE']._serialized_end=213
  _globals['_GETRELATEDRESPONSE']._serialized_start=215
  _globals['_GETRELATEDRESPONSE']._serialized_end=273
  _globals['_TRAVERSEREQUEST']._serialized_start=275
  _globals['_TRAVERSEREQUEST']._serialized_end=385
  _globals['_TRAVERSALNODE']._serialized_start=387
  _globals['_TRAVERSALNODE']._serialized_end=468
  _globals['_TRAVERSERESPONSE']._serialized_start=470
  _globals['_TRAVERSERESPONSE']._serialized_end=530
  _globals['_SETTHRESHOLDREQUEST']._serialized_start=532
  _globals['_SETTHRESHOLDREQUEST']._serialized_end=611
  _globals['_SETTHRESHOLDRESPONSE']._serialized_start=613
  _globals['_SETTHRESHOLDRESPONSE']._serialized_end=652
  _globals['_GRAPHSERVICE']._serialized_start=655
  _globals['_GRAPHSERVICE']._serialized_end=900
# @@protoc_insertion_point(module_scope)
