# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import vector_math_pb2 as swarndb_dot_v1_dot_vector__math__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in swarndb/v1/vector_math_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VectorMathServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DetectGhosts = channel.unary_unary(
                '/swarndb.v1.VectorMathService/DetectGhosts',
                request_serializer=swarndb_dot_v1_dot_vector__math__pb2.DetectGhostsRequest.SerializeToString,
                response_deserializer=swarndb_dot_v1_dot_vector__math__pb2.DetectGhostsResponse.FromString,
                _registered_method=True)
        self.ConeSearch = channel.unary_unary(
                '/swarndb.v1.VectorMathService/ConeSearch',
                request_serializer=swarndb_dot_v1_dot_vector__math__pb2.ConeSearchRequest.SerializeToString,
                response_deserializer=swarndb_dot_v1_dot_vector__math__pb2.ConeSearchResponse.FromString,
                _registered_method=True)
        self.ComputeCentroid = channel.unary_unary(
                '/swarndb.v1.VectorMathService/ComputeCentroid',
                request_serializer=swarndb_dot_v1_dot_vector__math__pb2.ComputeCentroidRequest.SerializeToString,
                response_deserializer=swarndb_dot_v1_dot_vector__math__pb2.ComputeCentroidResponse.FromString,
                _registered_method=True)
        self.Interpolate = channel.unary_unary(
                '/swarndb.v1.VectorMathService/Interpolate',
                request_serializer=swarndb_dot_v1_dot_vector__math__pb2.InterpolateRequest.SerializeToString,
                response_deserializer=swarndb_dot_v1_dot_vector__math__pb2.InterpolateResponse.FromString,
                _registered_method=True)
        self.DetectDrift = channel.unary_unary(
                '/swarndb.v1.VectorMathService/DetectDrift',
                request_serializer=swarndb_dot_v1_dot_vector__math__pb2.DetectDriftRequest.SerializeToString,
                response_deserializer=swarndb_dot_v1_dot_vector__math__pb2.DetectDriftResponse.FromString,
                _registered_method=True)
        self.Cluster = channel.unary_unary(
                '/swarndb.v1.VectorMathService/Cluster',
                request_serializer=swarndb_dot_v1_dot_vector__math__pb2.ClusterRequest.SerializeToString,
                response_deserializer=swarndb_dot_v1_dot_vector__math__pb2.ClusterResponse.FromString,
                _registered_method=True)
        self.ReduceDimensions = channel.unary_unary(
                '/swarndb.v1.VectorMathService/ReduceDimensions',
                request_serializer=swarndb_dot_v1_dot_vector__math__pb2.ReduceDimensionsRequest.SerializeToString,
                response_deserializer=swarndb_dot_v1_dot_vector__math__pb2.ReduceDimensionsResponse.FromString,
                _registered_method=True)
        self.ComputeAnalogy = channel.unary_unary(
                '/swarndb.v1.VectorMathService/ComputeAnalogy',
                request_serializer=swarndb_dot_v1_dot_vector__math__pb2.ComputeAnalogyRequest.SerializeToString,
                response_deserializer=swarndb_dot_v1_dot_vector__math__pb2.ComputeAnalogyResponse.FromString,
                _registered_method=True)
        self.DiversitySample = channel.unary_unary(
                '/swarndb.v1.VectorMathService/DiversitySample',
                request_serializer=swarndb_dot_v1_dot_vector__math__pb2.DiversitySampleRequest.SerializeToString,
                response_deserializer=swarndb_dot_v1_dot_vector__math__pb2.DiversitySampleResponse.FromString,
                _registered_method=True)


class VectorMathServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DetectGhosts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConeSearch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ComputeCentroid(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Interpolate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DetectDrift(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Cluster(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReduceDimensions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ComputeAnalogy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DiversitySample(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VectorMathServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DetectGhosts': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectGhosts,
                    request_deserializer=swarndb_dot_v1_dot_vector__math__pb2.DetectGhostsRequest.FromString,
                    response_serializer=swarndb_dot_v1_dot_vector__math__pb2.DetectGhostsResponse.SerializeToString,
            ),
            'ConeSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.ConeSearch,
                    request_deserializer=swarndb_dot_v1_dot_vector__math__pb2.ConeSearchRequest.FromString,
                    response_serializer=swarndb_dot_v1_dot_vector__math__pb2.ConeSearchResponse.SerializeToString,
            ),
            'ComputeCentroid': grpc.unary_unary_rpc_method_handler(
                    servicer.ComputeCentroid,
                    request_deserializer=swarndb_dot_v1_dot_vector__math__pb2.ComputeCentroidRequest.FromString,
                    response_serializer=swarndb_dot_v1_dot_vector__math__pb2.ComputeCentroidResponse.SerializeToString,
            ),
            'Interpolate': grpc.unary_unary_rpc_method_handler(
                    servicer.Interpolate,
                    request_deserializer=swarndb_dot_v1_dot_vector__math__pb2.InterpolateRequest.FromString,
                    response_serializer=swarndb_dot_v1_dot_vector__math__pb2.InterpolateResponse.SerializeToString,
            ),
            'DetectDrift': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectDrift,
                    request_deserializer=swarndb_dot_v1_dot_vector__math__pb2.DetectDriftRequest.FromString,
                    response_serializer=swarndb_dot_v1_dot_vector__math__pb2.DetectDriftResponse.SerializeToString,
            ),
            'Cluster': grpc.unary_unary_rpc_method_handler(
                    servicer.Cluster,
                    request_deserializer=swarndb_dot_v1_dot_vector__math__pb2.ClusterRequest.FromString,
                    response_serializer=swarndb_dot_v1_dot_vector__math__pb2.ClusterResponse.SerializeToString,
            ),
            'ReduceDimensions': grpc.unary_unary_rpc_method_handler(
                    servicer.ReduceDimensions,
                    request_deserializer=swarndb_dot_v1_dot_vector__math__pb2.ReduceDimensionsRequest.FromString,
                    response_serializer=swarndb_dot_v1_dot_vector__math__pb2.ReduceDimensionsResponse.SerializeToString,
            ),
            'ComputeAnalogy': grpc.unary_unary_rpc_method_handler(
                    servicer.ComputeAnalogy,
                    request_deserializer=swarndb_dot_v1_dot_vector__math__pb2.ComputeAnalogyRequest.FromString,
                    response_serializer=swarndb_dot_v1_dot_vector__math__pb2.ComputeAnalogyResponse.SerializeToString,
            ),
            'DiversitySample': grpc.unary_unary_rpc_method_handler(
                    servicer.DiversitySample,
                    request_deserializer=swarndb_dot_v1_dot_vector__math__pb2.DiversitySampleRequest.FromString,
                    response_serializer=swarndb_dot_v1_dot_vector__math__pb2.DiversitySampleResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swarndb.v1.VectorMathService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('swarndb.v1.VectorMathService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VectorMathService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DetectGhosts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swarndb.v1.VectorMathService/DetectGhosts',
            swarndb_dot_v1_dot_vector__math__pb2.DetectGhostsRequest.SerializeToString,
            swarndb_dot_v1_dot_vector__math__pb2.DetectGhostsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConeSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swarndb.v1.VectorMathService/ConeSearch',
            swarndb_dot_v1_dot_vector__math__pb2.ConeSearchRequest.SerializeToString,
            swarndb_dot_v1_dot_vector__math__pb2.ConeSearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ComputeCentroid(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swarndb.v1.VectorMathService/ComputeCentroid',
            swarndb_dot_v1_dot_vector__math__pb2.ComputeCentroidRequest.SerializeToString,
            swarndb_dot_v1_dot_vector__math__pb2.ComputeCentroidResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Interpolate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swarndb.v1.VectorMathService/Interpolate',
            swarndb_dot_v1_dot_vector__math__pb2.InterpolateRequest.SerializeToString,
            swarndb_dot_v1_dot_vector__math__pb2.InterpolateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DetectDrift(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swarndb.v1.VectorMathService/DetectDrift',
            swarndb_dot_v1_dot_vector__math__pb2.DetectDriftRequest.SerializeToString,
            swarndb_dot_v1_dot_vector__math__pb2.DetectDriftResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Cluster(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swarndb.v1.VectorMathService/Cluster',
            swarndb_dot_v1_dot_vector__math__pb2.ClusterRequest.SerializeToString,
            swarndb_dot_v1_dot_vector__math__pb2.ClusterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReduceDimensions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swarndb.v1.VectorMathService/ReduceDimensions',
            swarndb_dot_v1_dot_vector__math__pb2.ReduceDimensionsRequest.SerializeToString,
            swarndb_dot_v1_dot_vector__math__pb2.ReduceDimensionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ComputeAnalogy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swarndb.v1.VectorMathService/ComputeAnalogy',
            swarndb_dot_v1_dot_vector__math__pb2.ComputeAnalogyRequest.SerializeToString,
            swarndb_dot_v1_dot_vector__math__pb2.ComputeAnalogyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DiversitySample(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swarndb.v1.VectorMathService/DiversitySample',
            swarndb_dot_v1_dot_vector__math__pb2.DiversitySampleRequest.SerializeToString,
            swarndb_dot_v1_dot_vector__math__pb2.DiversitySampleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
