# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: swarndb/v1/vector.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'swarndb/v1/vector.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as swarndb_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17swarndb/v1/vector.proto\x12\nswarndb.v1\x1a\x17swarndb/v1/common.proto\"{\n\rInsertRequest\x12\x12\n\ncollection\x18\x01 \x01(\t\x12\"\n\x06vector\x18\x02 \x01(\x0b\x32\x12.swarndb.v1.Vector\x12&\n\x08metadata\x18\x03 \x01(\x0b\x32\x14.swarndb.v1.Metadata\x12\n\n\x02id\x18\x04 \x01(\x04\"-\n\x0eInsertResponse\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x0f\n\x07success\x18\x02 \x01(\x08\"2\n\x10GetVectorRequest\x12\x12\n\ncollection\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\x04\"k\n\x11GetVectorResponse\x12\n\n\x02id\x18\x01 \x01(\x04\x12\"\n\x06vector\x18\x02 \x01(\x0b\x32\x12.swarndb.v1.Vector\x12&\n\x08metadata\x18\x03 \x01(\x0b\x32\x14.swarndb.v1.Metadata\"\x8b\x01\n\rUpdateRequest\x12\x12\n\ncollection\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\x04\x12\'\n\x06vector\x18\x03 \x01(\x0b\x32\x12.swarndb.v1.VectorH\x00\x88\x01\x01\x12&\n\x08metadata\x18\x04 \x01(\x0b\x32\x14.swarndb.v1.MetadataB\t\n\x07_vector\"!\n\x0eUpdateResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"5\n\x13\x44\x65leteVectorRequest\x12\x12\n\ncollection\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\x04\"\'\n\x14\x44\x65leteVectorResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"<\n\x12\x42ulkInsertResponse\x12\x16\n\x0einserted_count\x18\x01 \x01(\x04\x12\x0e\n\x06\x65rrors\x18\x02 \x03(\t2\xed\x02\n\rVectorService\x12?\n\x06Insert\x12\x19.swarndb.v1.InsertRequest\x1a\x1a.swarndb.v1.InsertResponse\x12\x42\n\x03Get\x12\x1c.swarndb.v1.GetVectorRequest\x1a\x1d.swarndb.v1.GetVectorResponse\x12?\n\x06Update\x12\x19.swarndb.v1.UpdateRequest\x1a\x1a.swarndb.v1.UpdateResponse\x12K\n\x06\x44\x65lete\x12\x1f.swarndb.v1.DeleteVectorRequest\x1a .swarndb.v1.DeleteVectorResponse\x12I\n\nBulkInsert\x12\x19.swarndb.v1.InsertRequest\x1a\x1e.swarndb.v1.BulkInsertResponse(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'swarndb.v1.vector_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INSERTREQUEST']._serialized_start=64
  _globals['_INSERTREQUEST']._serialized_end=187
  _globals['_INSERTRESPONSE']._serialized_start=189
  _globals['_INSERTRESPONSE']._serialized_end=234
  _globals['_GETVECTORREQUEST']._serialized_start=236
  _globals['_GETVECTORREQUEST']._serialized_end=286
  _globals['_GETVECTORRESPONSE']._serialized_start=288
  _globals['_GETVECTORRESPONSE']._serialized_end=395
  _globals['_UPDATEREQUEST']._serialized_start=398
  _globals['_UPDATEREQUEST']._serialized_end=537
  _globals['_UPDATERESPONSE']._serialized_start=539
  _globals['_UPDATERESPONSE']._serialized_end=572
  _globals['_DELETEVECTORREQUEST']._serialized_start=574
  _globals['_DELETEVECTORREQUEST']._serialized_end=627
  _globals['_DELETEVECTORRESPONSE']._serialized_start=629
  _globals['_DELETEVECTORRESPONSE']._serialized_end=668
  _globals['_BULKINSERTRESPONSE']._serialized_start=670
  _globals['_BULKINSERTRESPONSE']._serialized_end=730
  _globals['_VECTORSERVICE']._serialized_start=733
  _globals['_VECTORSERVICE']._serialized_end=1098
# @@protoc_insertion_point(module_scope)
