apiVersion: v1
kind: LimitRange
metadata:
  name: swarndb-limits
  namespace: swarndb
  labels:
    app.kubernetes.io/name: swarndb
    app.kubernetes.io/component: resource-policy
spec:
  limits:
    - type: Container
      default:
        cpu: "2"
        memory: 4Gi
      defaultRequest:
        cpu: 500m
        memory: 1Gi
      max:
        cpu: "4"
        memory: 8Gi
    - type: Pod
      max:
        cpu: "4"
        memory: 8Gi
