apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: swarndb
  namespace: swarndb
  labels:
    app.kubernetes.io/name: swarndb
    app.kubernetes.io/component: network
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: swarndb
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - protocol: TCP
          port: 8080   # REST API
        - protocol: TCP
          port: 50051  # gRPC API
