apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: swarndb-data
  namespace: swarndb
  labels:
    app.kubernetes.io/name: swarndb
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
