apiVersion: v1
kind: ServiceAccount
metadata:
  name: swarndb
  namespace: swarndb
  labels:
    app.kubernetes.io/name: swarndb
    app.kubernetes.io/part-of: swarndb
automountServiceAccountToken: false
