apiVersion: v2
name: swarndb
description: A Helm chart for SwarnDB - high-performance vector database
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - vector-database
  - similarity-search
  - hnsw
  - grpc
home: https://github.com/chirotpaldas/swarndb
maintainers:
  - name: Chirotpal Das
